

services:
  fastapi:
    build: ./app
    container_name: weather-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING:-}
    networks:
      - observability-net



  grafana:
    image: grafana/grafana:latest
    container_name: weather-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./infra-local/grafana-provisioning:/etc/grafana/provisioning
    networks:
      - observability-net

networks:
  observability-net:
    driver: bridge

